In [76]:
import mysql.connector
import pandas as pd

In [77]:
# Database Connection
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="online_learning_experience_survey")

In [78]:
# Read data from MySQL
query = "SELECT * FROM response"
Survey = pd.read_sql(query, conn)

conn.close()

C:\Users\sahay\AppData\Local\Temp\ipykernel_15040\2731237424.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  Survey = pd.read_sql(query, conn)

In [79]:
Survey.head()

   id response_id poll_option             age_group           timestamp
0   1      RESP_1   Excellent        School Student 2026-02-06 10:22:37
1   2      RESP_2     Average       College Student 2026-02-06 10:23:22
2   3      RESP_3     Average  Working Professional 2026-02-06 10:23:29
3   4      RESP_4   Excellent                Others 2026-02-06 10:23:37
4   5      RESP_5   Excellent                       2026-02-06 10:23:42

In [80]:
Survey.shape

(95, 5)

In [81]:
Survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           95 non-null     int64
 1   response_id  95 non-null     object
 2   poll_option  95 non-null     object
 3   age_group    95 non-null     object
 4   timestamp    95 non-null     datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 3.8+ KB

In [82]:
Survey.isnull().sum()

id             0
response_id    0
poll_option    0
age_group      0
timestamp      0
dtype: int64

1.	Total number of responses

In [83]:
Total_responses = len(Survey)
Total_responses

95

2.	Frequency count of each poll option

In [84]:
Survey['poll_option'].value_counts()

poll_option
Excellent    31
Good         25
Average      23
Poor         16
Name: count, dtype: int64

3.	Percentage distribution of responses

In [85]:
percentage_distribution = (Survey['poll_option'].value_counts(normalize=True) * 100)
percentage_distribution

poll_option
Excellent    32.631579
Good         26.315789
Average      24.210526
Poor         16.842105
Name: proportion, dtype: float64

Most and least selected options

In [86]:
most_selected = Survey['poll_option'].value_counts().idxmax()  #it returns the name of the option
most_selected

'Excellent'

In [87]:
least_selected = Survey['poll_option'].value_counts().idxmin()
least_selected

'Poor'

5.	Trend analysis (if timestamps are used)

In [88]:
Survey['timestamp'] = pd.to_datetime(Survey['timestamp'])
Survey.groupby(Survey['timestamp'].dt.date).size()

timestamp
2026-02-06    50
2026-02-07    10
2026-02-10     4
2026-02-11     1
2026-02-16    30
dtype: int64

6.	Group-based analysis (e.g., age group vs choice)

In [89]:
group_based = pd.crosstab(Survey['age_group'], Survey['poll_option']) #Compares age group with option
group_based

poll_option           Average  Excellent  Good  Poor
age_group
                            2          4     1     0
College Student             4          7     8     3
Others                      7          3     3     4
School Student              4          5     3     2
Working Professional        6         12    10     7

●	Export cleaned data to CSV using Python

In [90]:
Survey.to_csv('Polling System Cleaned Data.csv')